name: "🎤 릴리즈"
description: 새로운 버전 릴리즈시 사용합니다.
title: "🎤 Release: "
labels: ["Release"]
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: 개요
      description: 작업 개요를 작성합니다.
    validations:
      required: true

  - type: input
    id: input-1
    attributes:
      label: 버전
      description: 버전을 지정합니다.
      placeholder: "1.2.0"

  - type: input
    id: input-2
    attributes:
      label: 릴리즈 일자
      description: 릴리즈 일자를 지정합니다.
      placeholder: "2025-10-01 수"

  - type: textarea
    id: textarea-3
    attributes:
      label: 비고
      value: 없음
